### Site Settings ###
title               : Mohit Mayank
description         : >-
                      Data Scientist @ TCS :bowtie:, AI/ML Researcher, Technology content creator, programmer and budding guitarist 🎸
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : imohitmayank/imohitmayank     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji
  - jekyll-feed

avatar: "/img/website_thumbnail.png"


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Mohit Mayank
  image             : img/avatar.jpg
  # behance           : your_username
# dribbble          : your_username
  googlescholar     : citations?user=LnW2hcYAAAAJ&hl=en
  email             : mohitmayank1@gmail.com
  # facebook          : your_username
  github            : imohitmayank
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : imohitmayank
  medium            : MohitMayank
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : imohitmayank
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  visual:
    output: true
    permalink: /visual/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus: "mohitmayank"                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: "UA-150752882-1"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "visual"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
